blueprint:
  name: "Pager tracking Person"
  description: "Tænder eller slukker for en input_boolean baseret på, om en device_tracker træder ind eller ud af en zone, og om en persons tilstand matcher en bestemt værdi."
  domain: automation
  input:
    device:
      name: "Device"
      description: "Vælg den enhed, som din device_tracker er tilknyttet."
      selector:
        device: {}
    device_tracker:
      name: "Device Tracker Entity"
      description: "Vælg den device_tracker-entity, der skal overvåges."
      selector:
        entity:
          domain: device_tracker
    zone:
      name: "Zone"
      description: "Vælg den zone, som device_tracker skal træde ind/ud af."
      selector:
        entity:
          domain: zone
    person:
      name: "Person"
      description: "Vælg den person-entity, som skal kontrolleres."
      selector:
        entity:
          domain: person
    target_state:
      name: "Måltilstand"
      description: "Navnet fra zonen FX Billund Brandstation"
      default: "n"
      selector:
        text: {}
    toggle_boolean:
      name: "Toggle Boolean"
      description: "Vælg den Person hjælper som skal bruges."
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: device
    device_id: !input device
    domain: device_tracker
    entity_id: !input device_tracker
    type: enters
    zone: !input zone
  - platform: device
    device_id: !input device
    domain: device_tracker
    entity_id: !input device_tracker
    type: leaves
    zone: !input zone

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input person
            state: !input target_state
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input toggle_boolean
    default:
      - service: input_boolean.turn_off
        target:
          entity_id: !input toggle_boolean
mode: single
